"""initial migration-3

Revision ID: 8ecda48ab93c
Revises: beaf044649e7
Create Date: 2026-01-16 18:02:45.539505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ecda48ab93c'
down_revision: Union[str, Sequence[str], None] = 'beaf044649e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
